---
- name: Include preflight checks
  import_tasks: preflight.yml
  tags:
    - journald
    - journald-preflight

- name: Include configuration tasks
  import_tasks: configure.yml
  tags:
    - journald
    - journald-configure
