---
galaxy_info:
  role_name: ziti_router
  author: neox5
  description: OpenZiti edge router via APT package for Debian 13 Trixie
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - openziti
    - overlay
    - zerotrust
    - networking

dependencies: []
