---
# Caddy role handlers

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted

- name: update ca certificates
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true
