---
galaxy_info:
  role_name: excalidraw
  author: neox5
  description: Self-hosted Excalidraw stack via Podman Quadlet (frontend + collaboration server)
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - containers
    - podman
    - excalidraw

dependencies: []
