n8n_db_password_secret: ENC[AES256_GCM,data:sABvSSIdUIMRvoL564B6i8Orv8BT/aB026akrSnxLIIHr+DJ6OoLX+snCujaGWC3TdC6fnyl3un6iiSuiugE8A==,iv:AaNtHFIcrdF5rnAsg6vWF6QDK9wUH6HOWrT1ZJ1wRPk=,tag:abWx4DAprxL9rir4QCLlEw==,type:str]
n8n_encryption_key_secret: ENC[AES256_GCM,data:y3nh0ANb+00VURXwIrJs4g7a5w5wGRs1HhBg8G16iJ3IBolGtm6zPR33ubfDdMtppcKEDlkEuImFB2cdiLFcmg==,iv:2rX6OezKzDL9f9srN3KyDMsmehbWzuXpdzkXd4w/aDI=,tag:6r8uVoZBz2mVUQDXBAk/Ww==,type:str]
restic_local_password_secret: ENC[AES256_GCM,data:Ua5BKJof3tx7WuGvMaeac+DXwijsffI/SAfZAK1H0MGXridKkFvzaLcFwLAUxAURNXjJJltBh7Bqycudf4QORw==,iv:UXnrmqK98bOcECx8YKoI9vbYBm2vXfbpbpPkwR+FDuA=,tag:i6DdUeb+O4dB1ZYQY5MEEQ==,type:str]
restic_b2_password_secret: ENC[AES256_GCM,data:48FldhXt+FPydTXIFDwv31u/PPldT93JJSwkDLf30pozdALi3CCT4WCBsfeF87qHILDCovcFwewvHYhitUh7vA==,iv:ZgzZMsk5QmcPPxPCHi+cOLVUh+Aqu+WOT7WdBfoLDFo=,tag:aQrgC4lS3UONfTbjDYLYCQ==,type:str]
restic_b2_key_id_secret: ENC[AES256_GCM,data:7FigDPf792dV64xE7RZ9gYmoehgpWihlOw==,iv:ntvUuZapsTegpEqSXE8GkDENtzMLKM9ZiiaazcT9t1I=,tag:GRYwLMF7HwiAoblSNSIr6g==,type:str]
restic_b2_key_secret_secret: ENC[AES256_GCM,data:Qz8wUhJJNIeqBbCsnBcpKnXv1uVH09c0vrDjL18geA==,iv:8bvN8BexBldvqKviADBwEHSbg/NqgKSdbPUgAZNZSAQ=,tag:K9n1LUKa0x85F8P7MseL+A==,type:str]
stepca_key_password: ENC[AES256_GCM,data:10XOEpt+yRvkfXD9JRpqi7Mz3S7eNk8WbwRVUMuZJ3Jt2qT1zX1iEpuNsAv4iwr4JyLikpyhJVZMn0TFINU7qg==,iv:9CCqpRAbra3d7DlWFx0yU7tnUYiX06DQEfipecJdGmE=,tag:e4xKABTPkETFwaTNq+r9zA==,type:str]
stepca_db_password: ENC[AES256_GCM,data:i88ah0q0Mn5nyn6ox9Z/YLuNEJsTAaBoP5Sojsz1FuotmZua5XopkXyyiImnLr0neLaNERs4u451WawHurbwZg==,iv:bLYdVWI+xQUi5WCKZwFTObf1NQSkxr/EvI0OqAykgRY=,tag:8l7oox1NuQHxmhai+iOFYA==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTURrallQTFM2SkhicDN5
            ekM5QlgvQTJTMHk4UnBaeURNMUgxZVMzWXh3CnNGeGtZYURwVzl6a2c3N29VYjlN
            eEE0QmRzSmUrRFhwZmxzM0NPenk1Q00KLS0tIFRjZ2dORWZyT3cxZEhiTGxlZzBl
            d01nRmhIQTdHVmNhNUNocDFKWDBOemsKzwP86Cj+WEDWmhruQUzWMH7tr+q6UJtU
            O29Y1d/1Cag7fc9QlWvKp2pdsRZpRuioqFnSb+cvFfQ/tEpsICA95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:32:37Z"
    mac: ENC[AES256_GCM,data:2H5cdLsQSuosjB76d46OkZBbfNnw39mGqequKesI+3/Au+yvPacIgqIUgoo0S2wwZU1oUi+ZBNJqA00UGEUSzAKWWl7Jn5VamVf/cKiga0VcZCCRdo8N1y0WB7eKVOZ9ocVyZT20t/j4LyTYKfcr6Hegp9jM/u+niDk6sA/nLYw=,iv:3e7Wfc8ZwafPlc8DFduWzHCAdksHa3es2cM5jWSHskA=,tag:2ikwOyvsxUS3t58g4XJrkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
