---
galaxy_info:
  role_name: headscale
  author: neox5
  description: Headscale coordination server for Debian 13 Trixie
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - networking
    - vpn
    - headscale
    - tailscale
    - wireguard

dependencies: []
