bootstrap_root_password_secret: ENC[AES256_GCM,data:AY/mA5P1Jw+IAT9Ep8NvKhsK+IkYmR0ZPK9XB53EVNyUPh9C/XjQ6SSMB8s6n/kBN7Vdi4pB7RC8ZRwtL0JqeA==,iv:Kfo34qK9CA7+7I7Wi7DcJ8SrueELGNKVxGGMA7U3ZrI=,tag:W9LnrRVm5FhNDgjaVrhEdQ==,type:str]
bootstrap_root_password_hash_secret: ENC[AES256_GCM,data:MrVLADzKFbP5BKdUZBx+YO+EIV0xYu1DaTHsZFtsjH1QCJ6U7yoBFVeGrmqG7vC8MSvTueQFyZcC2Ok6E8p4vpJzOCeR3WZyLz4H/YLFJVjUtkB3QacxuyyrknQxI8QzSbgAnnWkdwX+/w==,iv:M282JrH2ivWVgwLjC2203C8NL0LoGJHJrZEl6FLpK1k=,tag:bhPKNBhIDpiqVOEq6XGgLw==,type:str]
ziti_admin_password_secret: ENC[AES256_GCM,data:CGtVadOWlT8qeKhnN3FAvOc/6zTpXwZdZzvCz2bI5Qc1+BxuffhUv5wmXmX3YNo64QUbC2JSwfzWpAP+fwO2LA==,iv:TeMsZS3p1W7hDF8xbNS4S87bHO0WsAef58XqbBFVbGM=,tag:f1LAr97xpDKiUmQ69Wh2Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNVFyRnJsUVRKR3JXcVBo
            VEZ1NVc4aEt5cjBMcE91ZHQ0RTd2Q1FKT0M0CmIwL0JDL25rSmt6dFVVQU4wZUVt
            M3plVWc0NWxZeHFwd3JSRG9vTXUxbk0KLS0tIGM0Uk5jdjFocTFuQnBKOXQrU21Q
            THR2dmVKUVdocnlKd3hhdGJwb3BFRzQK6mSW9eD7pGOXcSp65hmWI2OGQNx5lq7a
            gYhdjpBfJfPrc+9xF/lLiiSVLHo/MiOO0m0oz418QBG92Uz1MJXtGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
    lastmodified: "2026-07-15T06:41:16Z"
    mac: ENC[AES256_GCM,data:mSDyGHKMYM28cQD7x6lpXzBtWqfen1wMZ23K3/fzmf24BZ4y75IUGfm0lZxpgig0ZXKye+JbAdHAaqCPLLhaw0OOOiMbQP56ASipXqNF862EdzChQxUh5oMcXcMY0C1RqjSpfpW5idA8dDOKLJFLHxFhrqcn9IJh4MvFaGweMBo=,iv:o9XtwNud6NpyUkEh8FNrhD7ePSIbk7GiIgE2SsxF2WE=,tag:lIf8qqAiodRIDMUB9vYrQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
