bootstrap_root_password_secret: ENC[AES256_GCM,data:AY/mA5P1Jw+IAT9Ep8NvKhsK+IkYmR0ZPK9XB53EVNyUPh9C/XjQ6SSMB8s6n/kBN7Vdi4pB7RC8ZRwtL0JqeA==,iv:Kfo34qK9CA7+7I7Wi7DcJ8SrueELGNKVxGGMA7U3ZrI=,tag:W9LnrRVm5FhNDgjaVrhEdQ==,type:str]
bootstrap_root_password_hash_secret: ENC[AES256_GCM,data:MrVLADzKFbP5BKdUZBx+YO+EIV0xYu1DaTHsZFtsjH1QCJ6U7yoBFVeGrmqG7vC8MSvTueQFyZcC2Ok6E8p4vpJzOCeR3WZyLz4H/YLFJVjUtkB3QacxuyyrknQxI8QzSbgAnnWkdwX+/w==,iv:M282JrH2ivWVgwLjC2203C8NL0LoGJHJrZEl6FLpK1k=,tag:bhPKNBhIDpiqVOEq6XGgLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNVFyRnJsUVRKR3JXcVBo
            VEZ1NVc4aEt5cjBMcE91ZHQ0RTd2Q1FKT0M0CmIwL0JDL25rSmt6dFVVQU4wZUVt
            M3plVWc0NWxZeHFwd3JSRG9vTXUxbk0KLS0tIGM0Uk5jdjFocTFuQnBKOXQrU21Q
            THR2dmVKUVdocnlKd3hhdGJwb3BFRzQK6mSW9eD7pGOXcSp65hmWI2OGQNx5lq7a
            gYhdjpBfJfPrc+9xF/lLiiSVLHo/MiOO0m0oz418QBG92Uz1MJXtGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
    lastmodified: "2026-08-01T20:41:10Z"
    mac: ENC[AES256_GCM,data:8oVcxNN5AABPyqx45No0CZ4FQasP2j/rlbiJkaPkQgcNtq8Gks737XaVpNVkuuBy0JHBMBdkaMZdClOvOKRI7COllMgbdpd1RUSc3p2j6358pbyy5+u4tmWqBIrPxrP13tcfBHMmQznLuLc+SxfFbLMTrhKP0IwLVGyVwaSBXi4=,iv:ugZ5aHsikx/cYc9eNiH0dMzz9gR4w1Dz4PL1fKONssA=,tag:i7NCjy/c4qZCrju+VBduGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
