ziti_admin_password_secret: ENC[AES256_GCM,data:cw1aEhhGX9rLh/QZ7E6wmE2lRi6O8Dkmk3LsC5acBZrsF/vWcvNC8zUC2Ar6teosN/NAQCbBTDXwvG3nByiqwg==,iv:iYoLS6sqm8QVxcQtZVIGNGQqQYMKguJ3q4MrfTD2UcA=,tag:dGghC4KV+dDLagzAlIYp+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UEFGM3lIV2hlM0Vicmpn
            UXZpZDF2MnlJdklNem9QcTN3bzBJMDVOcTFJCnZVS011b1RxL3RYSTB1Nm1OcnY5
            NXRLdERRQU03eDFLSTVZMkdUN0xiZ1kKLS0tIGVJMUcvS1hVQy9NSDZPdkVPTTRp
            ZERrMUFCbnB5OWFoR0hXK1EyL25yODQKF28rneZUqhmQ313weqtJggAYkDMY9XNG
            YAaYIRuLHjbltdWniYC2GWJWcAkWXl0GDIA7xYCnPBxKZkvsgVcmjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
    lastmodified: "2026-08-01T20:38:43Z"
    mac: ENC[AES256_GCM,data:lBaQpGjlnkezNwVDULgtsfR99r8ORJvy3DJUnnb3fE6TQ+khX4lLI+C6GxnOqUy8s6bLQpc71JnW85Vkwyr1VMVgIjrN208WkuDDwTbaBafu70dCPu1Ph8drfGA1UHyWoZKeVHzAs2bSXLBzR6RddkaKOFAVptNfCesp1IKqDxo=,iv:R+yu9MFyQHnEuv5MULNQ5PFqMue0HjNSAhvmrzj9b8s=,tag:naWaiI09lmEvlN7bIg8+bQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
