---
# =============================================================================
# Headscale: heimdall host configuration
# File: host_vars/heimdall/headscale.yaml
# Role: headscale
# =============================================================================

headscale_domain: "hs.neox5.com"

# Embedded DERP server public IP (required when headscale_derp_embedded: true)
headscale_derp_embedded_ipv4: "152.53.16.16"
