bootstrap_root_password_secret: ENC[AES256_GCM,data:kcIG5xyogtnioO2OwslhH9rXV9Opzvc1nytvFekd5fK70v/10J94v6vf6oSVob/18KaCTu/YNHfl+Yt5qpaeFg==,iv:7HTeAs+UE4aS8JppJUfpGCswOA+R3+hQoAmBNNp6dow=,tag:G/2sfnc2d3k5vC5cSSmW9g==,type:str]
bootstrap_root_password_hash_secret: ENC[AES256_GCM,data:q+QEP36PW/l6C70gSltem8dQfw2VV+aqMcB5DvcR4oFPKwEb4pVsIayDwC+8L9ZXZeMiM8BNY+w3eCK+wRE2eoqbuOysWojheVhegcouG2Gfl3VcdBtAuiwNDjAMYJxYknKhOE9M84IeZQ==,iv:rJ2ABwMyUvicUIimPzhKzAZgSqAtWRwCOyo+nptcLYM=,tag:5P+RBmDSDEp1rx1UbR0XSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0E1RHh1anhxUjlvWTZt
            a3pxUXBCdnAvUFVld0R4VUNDSDFhVkJpOUNzCjhlWjhLVUl0NGRod0NmNjgyVHJh
            YTBheDVNZlpRYTRuQkcwZ0YzU25ycWsKLS0tIE5TYitBd0JOeXY4eHEzRTBvNHpj
            eEs4c1ZTTGNVakRnNHE0b2hSVzFZUW8KQtMBFKTptQiQlp3H9NVg2HdhGXar69qJ
            gQtr+KdDHMlX8wXgA6z7UOW74Tzswpg4LKY/UwLqS67nU7kyWKJ+XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
    lastmodified: "2026-06-25T09:13:32Z"
    mac: ENC[AES256_GCM,data:/VQImxiIBfUiSJAdxxSRx6/6YiXMEiwc0/k6Iq2G3/AzYD/GzuCRBRyhjw/orT7kGZpOhjuDLa95W9HeM8PI/Sdou5KnnmFWuQLBakvQjNHUU4fefrGqSCcFL85FqWoRmIqJU3GSt7+OxkHgHgnb5ncOvhjaQQZtVrNWu083uhY=,iv:Vz4N3SN184WTKTV9DrescRmnoQrMOvWQJwICmb4LqKA=,tag:+nJe959Wm68ALaQ70R1X0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
