- name: Assert valid state value
  ansible.builtin.assert:
    quiet: true
    that: ziti_controller_state in ['present', 'absent']
    fail_msg: "ziti_controller_state must be 'present' or 'absent'"

- name: Assert valid PKI mode value
  ansible.builtin.assert:
    quiet: true
    that: ziti_controller_pki_mode in ['native', 'external']
    fail_msg: "ziti_controller_pki_mode must be 'native' or 'external'"
  when: ziti_controller_state == 'present'
