---
galaxy_info:
  role_name: synapse
  author: neox5
  description: Matrix Synapse homeserver via APT package for Debian 13 Trixie
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - matrix
    - synapse
    - messaging

dependencies: []
