[lab]
lab-vm ansible_host=127.0.0.1 ansible_port=2222

[lab:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519_ansible
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
