---
# ============================================================================
# Certs: Lab n150 Configuration
# File: group_vars/n150/certs.yml
# Role: certs (custom)
# ============================================================================
#
# Applied to: All hosts in 'n150' group
# Variable precedence: all < n150 (this file) < host_vars

# CA certificates - installed into system trust store
# Content: paste PEM content of zion_root_ca_g1.cert.pem
ca_certs:
  - name: zion_root_ca_g1
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIB1zCCAVygAwIBAgIUPa014aG4GrDp/osOYWcS1rspLYYwCgYIKoZIzj0EAwMw
      GjEYMBYGA1UEAwwPWmlvbiBSb290IENBIEcxMB4XDTI2MDIyNDE5MjIxOFoXDTQ2
      MDIxOTE5MjIxOFowGjEYMBYGA1UEAwwPWmlvbiBSb290IENBIEcxMHYwEAYHKoZI
      zj0CAQYFK4EEACIDYgAEA8cnxAfIPmmiawghRTBm/FQzqqIZoLlJPD2TCotex/0E
      sti8bRyepUgGk/1+Wt0dUOltJPTIla9qJcPffdhmBZ5JamQwk8a8cRF6fdytuimR
      TlI8GzcnfB30y/sZKRYlo2MwYTAdBgNVHQ4EFgQUYE8+jk4Tnx43Bis7OvJ18VF1
      qIswHwYDVR0jBBgwFoAUYE8+jk4Tnx43Bis7OvJ18VF1qIswDwYDVR0TAQH/BAUw
      AwEB/zAOBgNVHQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwMDaQAwZgIxALBTIpXEpzrN
      nmk058wA7GECLjPI82tkL1hHl1UD5QjzSfi+EqoS4ZYG6gA2qiEXQAIxALIzPMnl
      bmD7KHDUt8V3OdyQhoDLWEG0FM5Ej9G+ggSFMSXB0Yw/kK7PgBRwApFUFQ==
      -----END CERTIFICATE-----
