# playbooks/ziti_controller.yaml
# Usage: ansible-playbook -i inventory/prod playbooks/ziti_controller.yaml -l eroc
---
- name: Deploy ziti_controller instances
  hosts: all
  become: true
  tasks:
    - name: Deploy ziti_controller instance (single)
      ansible.builtin.include_role:
        name: ziti_controller
      when: ziti_controller_instances is not defined

    - name: Deploy ziti_controller instances (multi)
      ansible.builtin.include_role:
        name: ziti_controller
      vars:
        ziti_controller_id: "{{ item.ziti_controller_id }}"
        ziti_ctrl_advertised_address: "{{ item.ziti_ctrl_advertised_address }}"
        ziti_ctrl_advertised_port: "{{ item.ziti_ctrl_advertised_port }}"
        ziti_controller_pki_mode: "{{ item.ziti_controller_pki_mode | default('native') }}"
      loop: "{{ ziti_controller_instances | default([]) }}"
      when: ziti_controller_instances is defined
      loop_control:
        label: "{{ item.ziti_controller_id }}"
