n8n_db_password_secret: ENC[AES256_GCM,data:ffa/F6VOMtRFGmujec5igzKk7g3F2emAOWzp9AhfjgG7FxAt7R9Z1vPBWYKXiIiWkCens9Rsg1GnloFWoQWh7g==,iv:w3TgtRWEdRJE48iXV9c/xijAcFB0xeH4t2mjC/3z/SM=,tag:NBoaQd1vDgzVfCmpogm1Iw==,type:str]
n8n_encryption_key_secret: ENC[AES256_GCM,data:vBzCbAOkq0T7hJvnel/jhtmRgl95Ph7+slSiscHbiy+/JhK/MbnnITyocmHB5nAPj22rKJgxPw2NDUzd5wwM6Q==,iv:eb5jQ7s+4fVhp39Vymj7kL5Zg+DNB83DfIdUTgAV+s0=,tag:iHiIXex350UnED3lIlq46w==,type:str]
restic_local_password_secret: ENC[AES256_GCM,data:O50Mj5B5HOxpp367IvFUTXGCA5sSdxIbU4yDPQCG/UJd5XhHZgrfgkvthcdWCoglEz7OwuXxfirRUT9SnXC9Wg==,iv:0XE3D4QN9wGNK/GKtZXG2N+i/kmiaHHh+Mb9u19andE=,tag:1kjIxQsDU4gxHpaggISzuw==,type:str]
restic_b2_password_secret: ENC[AES256_GCM,data:CLaSDbVowgClzBFmsEJNWxBAck8g8yTz0LrEZL699ABnon9+c80MUqHLRggGP64uVvUlHLssjOnMcei94awgOQ==,iv:/PNNN+Fpf4rExG+99GzsN8umzolteBp7axm2Vy4eeb8=,tag:9/laUx18SL4aef4ZjgvGLQ==,type:str]
restic_b2_key_id_secret: ENC[AES256_GCM,data:5xBP7Pi36IfAn7HH7bxOUb2N89AHu/QE+A==,iv:ef10XAl0wFfaLoTy85Lk0TChaPUKcPfJGDWX1xXBmQA=,tag:XuPnne8R2zlwnFL2XG8y0g==,type:str]
restic_b2_key_secret_secret: ENC[AES256_GCM,data:a/ddOZ/6EeI0qp6ulf3nr5UXptWq5+XcEnGiZehUIQ==,iv:zabCXIcZwuYQd3KQpXle267Nh4jJt4N71yjKh/cZ+V0=,tag:q4puTI4OW/MbmnwiyfBhng==,type:str]
sops:
    age:
        - recipient: age1fmdqnls7zgddw7qxdn3rtwlk878rfly77pqw56fz7p38j36h4gtq6hsh0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkg2T3NFSFpyWkhnejhh
            d1dWclA2WnFPaS9kTEQzbUhvV1g0eHp4MG1jCk1kN2FmdlhPN0NxWWFXc0lkL0xP
            d2ZUWk1ybmg0RkVOMGZnNlZVbk9oUmsKLS0tIGdoOHZlNmV1U1JBeHRTeGZ2QWpk
            eHFub2J4UGFOdkkxOHhGMk8rdzI0MG8K8aYf3AEX+ZxTKR4dRgScUVtsz/R82ocI
            +maZLWu1rEBNPyLkVApd+o8ZE/cgU5tD3/3z9A2JleNBMlFSjvpHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:18:19Z"
    mac: ENC[AES256_GCM,data:u0UlZex49r7H3q9Iqy6qytw3FMlC/kr2mNpDw0FN+erKvRE53+E7cSNfDWX1smCHgB+z3ihentlm8xrXSn5jRX67sxjLuA+jFVuFzwngjae+311rt+FygcLWqlUrqdwDONuz0lKlWJCtcISYj18zo14OehvyrMVE+tUkh51iVhU=,iv:hJ+d/8k1//3kJ4CQlDcwU4K7qcqNzs4BPyGqOo/96V4=,tag:lTsoDDYGki85V2rS/U+GoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
